# Generated by Django 6.0.6 on 2026-06-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(choices=[('GENERAL_BED', 'General Bed'), ('ICU_BED', 'ICU Bed'), ('CABIN_BED', 'Cabin Bed'), ('VENTILATOR_BED', 'Ventilator Bed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='units_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('CHEST', 'Chest'), ('HEART', 'Heart'), ('ORTHO', 'Orthopedic'), ('GENERAL', 'General'), ('NEURO', 'Neurology'), ('PEDIATRIC', 'Pediatric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='opd_duration',
            field=models.PositiveIntegerField(help_text='OPD duration in minutes'),
        ),
    ]
